function darkMode(){localStorage.setItem("mode","darkmode"===localStorage.getItem("mode")?"light":"darkmode"),"darkmode"===localStorage.getItem("mode")?document.querySelector("#mainContent").classList.add("darkMode"):document.querySelector("#mainContent").classList.remove("darkMode")}; function gridMode(){localStorage.setItem("list","listmode"===localStorage.getItem("list")?"grid":"listmode"),"listmode"===localStorage.getItem("list")?document.querySelector("#mainContent").classList.add("gridMode"):document.querySelector("#mainContent").classList.remove("gridMode")}; function resizeHeaderOnScroll() {const distanceY = window.pageYOffset || document.documentElement.scrollTop, shrinkOn = 20, headerEl = document.getElementById('header');if (distanceY > shrinkOn) {headerEl.classList.add("show");} else {headerEl.classList.remove("show");} } window.addEventListener('scroll', resizeHeaderOnScroll); 
function copyFunction(){document.getElementById("getlink").select(),document.execCommand("copy"),document.getElementById("shareNotif").innerHTML="<span>Link copied!</span>" }; 

/* Lightbox image script, source: kompiajaib.com/2021/09/update-image-lightbox-dengan-css-dan.html */ 
for(var imageslazy=document.querySelectorAll(".postBody .separator img, .postBody .tr-caption-container img"),i=0;i<imageslazy.length;i++)imageslazy[i].setAttribute("onclick","return false");function wrap(o,i,t){for(var a=document.querySelectorAll(i),e=0;e<a.length;e++){var r=o+a[e].outerHTML+t;a[e].outerHTML=r}}wrap('<div class="zmImg">',".postBody .separator >a","</div>"),wrap('<div class="zmImg">',".postBody .tr-caption-container td >a","</div>"),wrap('<div class="zmImg">',".postBody .separator >img","</div>"),wrap('<div class="zmImg">',".postBody .tr-caption-container td >img","</div>");var containerimg=document.getElementsByClassName("zmImg");for(i=0;i<containerimg.length;i++)containerimg[i].onclick=function(){this.classList.toggle("s")};

/* Defer lazy */
Defer.dom(".lazy",100,"loaded",null,{rootMargin:"1px"}),"undefined"!=typeof infinite_scroll&&infinite_scroll.on("load",function(){Defer.dom(".lazy",100,"loaded",null,{rootMargin:"1px"})});

/* lazy youtube */
( function() {var youtube = document.querySelectorAll(".lazyYoutube"); for (var i = 0; i < youtube.length; i++) {var source = "https://img.youtube.com/vi/"+ youtube[i].dataset.embed +"/sddefault.jpg"; var image = new Image(); image.setAttribute("class", "lazy"); image.setAttribute("data-src",source); image.setAttribute("src","data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="); image.setAttribute("alt","Youtube video"); image.addEventListener( "load", function() {youtube[ i ].appendChild( image );}( i ) ); youtube[i].addEventListener( "click", function() {var iframe = document.createElement( "iframe" ); iframe.setAttribute( "frameborder", "0" ); iframe.setAttribute( "allowfullscreen", "" ); iframe.setAttribute( "src", "https://www.youtube.com/embed/"+ this.dataset.embed +"?rel=0&showinfo=0&autoplay=1" ); this.innerHTML = ""; this.appendChild( iframe ); }); }; })(); 

/* Pengaturan safeLink */
var setTimer = 20; //waktu detik
var setColor = '#f89000'; //warna loading timer
var setText = 'Harap Tunggu...'; //pesan pada tombol
var setCopyUrl = 'Salin URL'; // generator salin
var setCopied = 'URL Tersalin'; //generator tersalin
var setGotolink = 'Go To Link';

!function(){const e=document.querySelector("#my-safeModal"),n=document.querySelector("#safeModal-btn"),t=document.querySelector(".close");n.addEventListener("click",function(){e.style.display="block"}),t.addEventListener("click",function(){e.style.display="none"}),window.addEventListener("click",function(n){n.target==e&&(e.style.display="none")}),document.querySelector("#btngenerate").onclick=function(){var e=document.querySelector("#generateurl").value,n=document.querySelector("#generatelink"),t=document.querySelector("#generateloading"),r=document.querySelector("#resulturl");if(""==e)return document.querySelector("#generateurl").focus(),!1;document.querySelector("#copytoclipboard").innerHTML=setCopyUrl,t.classList.remove("hidden"),n.classList.add("hidden");var o=new XMLHttpRequest;o.onerror=function(){r.value="Error loading feed!"},o.onloadend=function(){if(""!==this.responseText){var o="",l=JSON.parse(this.responseText).feed.entry,c=new Array;if(void 0!==l){for(var a=0;a<l.length;a++){for(var d=0;d<l[a].link.length;d++)if("alternate"==l[a].link[d].rel){o=l[a].link[d].href;break}c[a]=o;var u=Math.random()*c.length;u=parseInt(u)}resultgenerate=c[u]+"#?o="+function(e){for(var n="0x",t=e.length,r=0;r<t;r++)n+=e.charCodeAt(r).toString(15);return n}(e.replace(/^\s+/,"").replace(/\s+$/,"")),t.classList.add("hidden"),n.classList.remove("hidden"),r.value=resultgenerate}else r.value="No result!"}},o.open("GET","/feeds/posts/summary?alt=json",!0),o.send()},document.querySelector("#copytoclipboard").addEventListener("click",function(e){e.preventDefault(),document.execCommand("copy",!1,document.getElementById("resulturl").select())}),urlParam=function(e){var n=new RegExp("[?&]"+e+"=([^&#]*)").exec(window.location.href);return null==n?null:decodeURI(n[1])||0}}();
